apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-macwen-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: date
          name: siteStartTime
          label: 建站时间
        - $formkit: text
          name: icp
          label: ICP 备案
          value: 京ICP备88888号
          placeholder: 请输入 ICP 备案号
          help: "京ICP备xxxxxxxx号"
        - $formkit: url
          name: copyrightAgreement
          label: 版权协议
          placeholder: "请输入版权协议地址"
          help: '文章模块声明版权，也会使用此协议'


    - group: header
      label: 首页
      formSchema:
        - $formkit: attachment
          name: header_logo
          label: 顶部LOGO
          placeholder: "请输入LOGO地址"
          help: '页脚导航LOGO'
        - $formkit: url
          name: banner_url
          label: 顶部banner按钮跳转链接
          placeholder: "请输入跳转地址"
          help: '输入你要跳转的地址'
        - $formkit: text
          name: banner_buttontext
          label: banner跳转按钮文字
          value: 立即下载
          placeholder: "按钮文字"
          help: '输入按钮名字，例如：立即下载'
        - $formkit: text
          name: banner_firsttext
          label: banner黑体文字
          value: Halo-theme - 一对一高品质定制服务
          placeholder: "请输入你想要的文字"
          help: '第一行黑体大字'
        - $formkit: text
          name: banner_secondtext
          label: banner灰体文字
          value: 提供精美设计，功能开发，打造你的专属halo应用下载主题。
          placeholder: "请输入你想要的文字"
          help: '第二行灰体字'
        - $formkit: text
          name: appPost_text
          label: 软件文模块文字
          value: 精品软件
        - $formkit: url
          name: categoryUrl
          label: 更多软件跳转地址
          value: ""
        - $formkit: repeater
          name: appPost
          label: 软件类模块文章输出分类
          help: '一个分类占一行，一行最多六个文章'
          value: [ ]
          children:
            - $formkit: categorySelect
              name: app_category
              label: 分类
        - $formkit: categorySelect
          name: category2
          label: 文档类文章输出分类
          value: ""
        - $formkit: text
          name: category2_text
          label: 文档分类显示文字
          value: 教程文章
          placeholder: "请输入你想要的文字"
          help: '输入该分类的名称，例如：教程文章'
        - $formkit: url
          name: docUrl
          label: 更多文章跳转地址
          value: ""
    - group: post
      label: 文章页
      formSchema:
        - $formkit: radio
          name: postRequired
          id: postRequired
          key: postRequired
          label: 安装必读
          value: false
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: postSelect
          if: "$get(postRequired).value"
          name: firstPost
          label: 左边文章（最大）
          help: "选择一篇必读的文章"
        - $formkit: postSelect
          if: "$get(postRequired).value"
          name: secondPost
          label: 右边上文章
          help: "选择一篇必读的文章"
        - $formkit: postSelect
          if: "$get(postRequired).value"
          name: thirdPost
          label: 右边上文章
          help: "选择一篇必读的文章"
        - $formkit: radio
          name: qqOpen
          id: qqOpen
          key: qqOpen
          label: QQ群
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: url
          if: "$get(qqOpen).value"
          name: qqUrl
          label: 加群链接
          help: "加入QQ群的加群链接"
        - $formkit: text
          if: "$get(qqOpen).value"
          name: qqText
          label: QQ群号
          help: "你的QQ群号"
        - $formkit: text
          if: "$get(qqOpen).value"
          name: qqTitle
          label: QQ群名称
          help: "例如：精品mac软件交流群"
        - $formkit: attachment
          if: "$get(qqOpen).value"
          name: qqCode
          label: 加群二维码
        - $formkit: radio
          name: sponsor
          id: sponsor
          key: sponsor
          label: 打赏
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: attachment
          if: "$get(sponsor).value"
          name: qqCollection
          label: QQ收款码
        - $formkit: attachment
          if: "$get(sponsor).value"
          name: wechatCollection
          label: 微信收款码
        - $formkit: attachment
          if: "$get(sponsor).value"
          name: alipayCollection
          label: 支付宝收款码
        - $formkit: textarea
          if: "$get(sponsor).value"
          name: thanks
          label: 说明
          placeholder: '<h6 class="fw-600 mb-0">帮助分担一部分运维成本。❤️🙏🤝</h6><p class="mb-0 text-muted">做好事也要留名的！打赏完后记得联系QQ：66303299 统计哦。</p>'
          help: "请输入HTML代码"
        - $formkit: text
          name: downName_first
          label: 下载地址一名称
          value: "立即下载"
        - $formkit: attachment
          name: downIcons_first
          label: 下载地址一图标
        - $formkit: text
          name: downName_second
          label: 下载地址二名称
          value: "立即下载"
        - $formkit: attachment
          name: downIcons_second
          label: 下载地址二图标
        - $formkit: text
          name: downName_third
          label: 下载地址三名称
          value: "立即下载"
        - $formkit: attachment
          name: downIcons_third
          label: 下载地址三图标






    - group: footer
      label: 页脚
      formSchema:
        - $formkit: attachment
          name: footer_logo
          label: 页脚LOGO
          placeholder: "请输入LOGO地址"
          help: '页脚导航LOGO'
    - group: box
      label: 专题分类
      formSchema:
        - $formkit: text
          name: box1_text
          label: 专题一文字
          value: 新人必备
          placeholder: "请输入专题文字"
          help: '第一个框显示的文字'
        - $formkit: url
          name: box1_url
          label: 专题一链接
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box2_text
          label: 专题二
          value: 图像处理工具
          placeholder: "请输入专题文字"
          help: '第二个框显示的文字'
        - $formkit: url
          name: box2_url
          label: 专题二
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box3_text
          label: 专题三
          value: 产品经理工具
          placeholder: "请输入专题文字"
          help: '第三个框显示的文字'
        - $formkit: url
          name: box3_url
          label: 专题三
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box4_text
          label: 专题四
          value: 更多专题
          placeholder: "请输入专题文字"
          help: '第四个框显示的文字'
        - $formkit: url
          name: box4_url
          label: 专题二
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'

    - group: special
      label: 专题
      formSchema:
        - $formkit: repeater
          name: specialselection
          label: 专题设置
          value: []
          children:
            - $formkit: text
              name: specialname
              label: 专题名称
              value: ""
            - $formkit: attachment
              name: specialcover
              label: 专题封面
              help: '选择专题封面'
            - $formkit: select
              name: special_specialSelect_type
              id: special_specialSelect_type
              key: special_specialSelect_type
              label: 专题跳转页
              value: tag
              options:
                - label: 标签
                  value: tag
                - label: 分类
                  value: category
            - $formkit: tagSelect
              if: "$get(special_specialSelect_type).value === tag"
              name: tag
              label: 选择跳转标签页
              value: ""
            - $formkit: categorySelect
              if: "$get(special_specialSelect_type).value === category"
              name: category
              label: 选择跳转分类页
              value: ""

    - group: menu
      label: 菜单
      formSchema:
        - $formkit: menuRadio
          name: menu_first
          label: 顶部输出导航
          value: ""
          help: '顶部黑色区域导航'
        - $formkit: menuRadio
          name: menu_top
          label: 导航栏
          value: ""
          help: 'LOGO随后的导航'
        - $formkit: menuRadio
          name: menu_foot
          label: 底部输出导航
          value: ""



