apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-macwen-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: date
          name: siteStartTime
          label: 建站时间
        - $formkit: text
          name: icp
          label: ICP 备案
          value: 京ICP备88888号
          placeholder: 请输入 ICP 备案号
          help: "京ICP备xxxxxxxx号"
        - $formkit: url
          name: copyrightAgreement
          label: 版权协议
          placeholder: "请输入版权协议地址"
          help: '文章模块声明版权，也会使用此协议'


    - group: header
      label: 顶部
      formSchema:
        - $formkit: attachment
          name: header_logo
          label: 顶部LOGO
          placeholder: "请输入LOGO地址"
          help: '页脚导航LOGO'
        - $formkit: url
          name: banner_url
          label: 顶部banner按钮跳转链接
          placeholder: "请输入跳转地址"
          help: '输入你要跳转的地址'
        - $formkit: text
          name: banner_buttontext
          label: banner跳转按钮文字
          value: 立即下载
          placeholder: "按钮文字"
          help: '输入按钮名字，例如：立即下载'
        - $formkit: text
          name: banner_firsttext
          label: banner黑体文字
          value: Halo-theme - 一对一高品质定制服务
          placeholder: "请输入你想要的文字"
          help: '第一行黑体大字'
        - $formkit: text
          name: banner_secondtext
          label: banner灰体文字
          value: 提供精美设计，功能开发，打造你的专属halo应用下载主题。
          placeholder: "请输入你想要的文字"
          help: '第二行灰体字'
        - $formkit: categoryCheckbox
          name: category2
          label: 文档类文章输出分类
          value: ""
        - $formkit: text
          name: category2_text
          label: 文档分类显示文字
          value: 教程文章
          placeholder: "请输入你想要的文字"
          help: '输入该分类的名称，例如：教程文章'

    - group: footer
      label: 页脚
      formSchema:
        - $formkit: attachment
          name: footer_logo
          label: 页脚LOGO
          placeholder: "请输入LOGO地址"
          help: '页脚导航LOGO'
    - group: box
      label: 专题分类
      formSchema:
        - $formkit: text
          name: box1_text
          label: 专题一文字
          value: 新人必备
          placeholder: "请输入专题文字"
          help: '第一个框显示的文字'
        - $formkit: url
          name: box1_url
          label: 专题一链接
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box2_text
          label: 专题二
          value: 图像处理工具
          placeholder: "请输入专题文字"
          help: '第二个框显示的文字'
        - $formkit: url
          name: box2_url
          label: 专题二
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box3_text
          label: 专题三
          value: 产品经理工具
          placeholder: "请输入专题文字"
          help: '第三个框显示的文字'
        - $formkit: url
          name: box3_url
          label: 专题三
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'
        - $formkit: text
          name: box4_text
          label: 专题四
          value: 更多专题
          placeholder: "请输入专题文字"
          help: '第四个框显示的文字'
        - $formkit: url
          name: box4_url
          label: 专题二
          placeholder: "请输入专题地址"
          help: '输入跳转的页面地址'

    - group: menu
      label: 菜单
      formSchema:
        - $formkit: menuRadio
          name: menu_top
          label: 顶部输出导航
          value: ""
          help: 'LOGO随后的导航'
        - $formkit: menuRadio
          name: menu_foot
          label: 底部输出导航
          value: ""
    - group:


