apiVersion: theme.halo.run/v1alpha1
kind: Theme
spec:
  customTemplates:
    post:
      - name: 文档
        description: 文档类型的文章
        screenshot:
        file: post_documentation.html
  specialTemplates:
    page:
      - name: 专题模板
        description: 专题专用模板
        screenshot:
        file: special.html
  displayName: macwen
  author:
    name: Jiewen
    website: 'https://jiewen.run'
  description: 一款移植自wp仿macwk的软件下载类模板
  logo: 'https://pic.tyubar.com/2022/11/1668877198-32b3773ec3c02dc.png'
  website: 'https://jiewen.run'
  repo: 'https://github.com/jiewenhuang/halo-theme-macwen'
  settingName: 'theme-macwen-setting'
  configMapName: 'theme-macwen-configMap'
  version: '1.1.0'
  requires: '>=2.1.0'
metadata:
  name: theme-macwen
